collections:
  authors:
    output: true

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

defaults:
  - scope:
      permalink: "/writers/:title/"
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      permalink: "/blog/:title/"
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-feed
